package AnalizadorLexico;

public enum Categoria {

    ENTERO,
    REAL,
    BOOLEAN,
    CARACTER,
    IDENTIFICADOR,
    PARENTESIS_ABRIR,
    PARENTESIS_CERRAR,
    CORCHETE_ABRIR,
    CORCHETE_CERRAR,
    LLAVES_ABRIR,
    LLAVES_CERRAR,
    FIN_SENTENCIA,
    CADENA_CARACTERES,
    PUNTO,
    OPERADOR_ARITMETICO,
    OPERADOR_LOGICO,
    OPERADOR_INCREMENTO,
    OPERADOR_DECREMENTO,
    SEPARADOR,
    ARREGLO,
    COMENTARIO_BLOQUE,
    COMENTARIO_LINEA,
    PALABRA_RESERVADA,
    FIN_CODIGO,
    OPERADOR_RELACIONAL,
    OPERADOR_ASIGNACION,
    TIPO_DATO_ENTERO,
    TIPO_DATO_DOBLE,
    TIPO_DATO_CARACTER,
    TIPO_DATO_CADENA,
    CICLO_MIENTRAS_INICIO,
    CICLO_MIENTRAS_FIN,
    DESCONOCIDO;

}
